### ISSUE TITLE
Shuffled list generator

### ISSUE THREAD

**Issue by NathanReb** [stedolan/crowbar#48]
Would you consider adding a:
```ocaml
val shuffle : 'a list -> 'a list gen
```
to `crowbar`? I have a use case for it and I think it could be a worthy addition generally speaking.

I'm happy to contribute if you feel like it should be part of the library!

**Comment by stedolan** [comment]
That does sound useful! I don't have time to work on it right now, but PRs welcome. (If you're unsure how, I think a good way of doing it is [this algorithm](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm) using `Crowbar.range` to pick the numbers.)

**Comment by NathanReb** [comment]
Yeah that's what I used in the end to shuffle my lists. I'll give it a go!

**Comment by NathanReb** [comment]
Hmm thought I added a mention to automatically close this in #50. I guess this can be closed now!
