### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by raphael-proust** [stedolan/crowbar#57]
There've been a lot of additions since the released version (`0.1`, February 2018). Is it time for a new release?

**Comment by Lupus** [comment]
Also `0.1` does not build with latest dune (at least when recent enough `~/.config/dune/config` is present), as it still uses `jbuilder`.

```
#=== ERROR while compiling crowbar.0.1 ========================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.1 | https://opam.ocaml.org#0b77d3f9
# path        ~/git/my-project/_opam/.opam-switch/build/crowbar.0.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build --only-packages crowbar --root . -j 12 @install
# exit-code   1
# env-file    ~/.opam/log/crowbar-13412-d2c37b.env
# output-file ~/.opam/log/crowbar-13412-d2c37b.out
### output ###
# File "/home/vagrant/.config/dune/config", line 1, characters 0-15:
# Error: S-expression of the form (_ _) expected
```

**Comment by raphael-proust** [comment]
@stedolan I can volunteer to prepare the relase and such if that would help

**Comment by stedolan** [comment]
Thanks for the poke! I'd forgotten about this, been meaning to. `v0.2` now exists, heading opamwards via ocaml/opam-repository#16349

**Comment by raphael-proust** [comment]
I'll close this now and re-open it if, for some reason, it doesn't land in opam.
